server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://kn.letters7.com:33308/twu?characterEncoding=utf-8&useSSL=false
    username: wuchenl
    password: g20130817!
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 4
    initial-size: 10
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.thoughtworks.nho.model
